version: '3.2'
services:
  router_dnsmasq:
    image: ${OWNER}/${REPO}-${ARCH}:${VERSION}
    
    restart: always

    network_mode: "host"

    cap_add:
      - NET_ADMIN

    volumes:
      - type: bind
        source: ${CONF_DIR}
        target: /dnsmasq/dnsmasq.d
