FROM alpine

RUN apk update && \
    apk upgrade && \
    apk add --update bash dnsmasq && \
    rm -rf /var/cache/apk/*

WORKDIR dnsmasq

COPY init ./
COPY dnsmasq.conf ./

VOLUME /dnsmasq/dnsmasq.d

ENTRYPOINT ./init
