FROM elespejo/armv6-x86-alpine-base 

MAINTAINER Phoenix Lv <phoenix.lv@dorry.io>

RUN apk update && \
    apk upgrade && \
    apk add --update bash vim dnsmasq && \
    rm -rf /var/cache/apk/*

WORKDIR dnsmasq

COPY init ./
COPY dnsmasq.conf ./

VOLUME /dnsmasq/dnsmasq.d

ENTRYPOINT ./init
