#!/bin/bash

DM="/dnsmasq/dnsmasq.conf"
DMD=`ls /dnsmasq/dnsmasq.d/*`


echo "Test dnsmasq configuration"
for f in $DMD
do
    echo $f
    dnsmasq --test -C $f
done


echo "dnsmasq starting ..." 
dnsmasq -k -C $DM
